FIND_PATH(SERVER_INCLUDE_DIR NAMES Server.hpp)
FIND_LIBRARY(SERVER_LIBRARY NAMES Server)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SERVER REQUIRED_VARS 
	SERVER_LIBRARY SERVER_INCLUDE_DIR)

IF(SERVER_FOUND)
    SET(SERVER_LIBRARIES ${SERVER_LIBRARY})
    SET(SERVER_INCLUDE_DIRS ${SERVER_INCLUDE_DIR})
ENDIF()